
BATCH_SIZE : !!int 3
EPOCHS : !!int  30
LEARNING_RATE : !!float 3e-2
SEED : !!int 0
EVALUATE_ON_DEV: True
EVALUATE_ON_TEST: False
TYPE_OF_PARSER: 'spider'  #['bobcat','spider','depccg']
DRAW : False
LAST_LAYER_NEURON_COUNT : !!int  1
USE_RANKER_FOR_PRED:  True #do you want to use plain 2-class classification or rank by score plus pick top N
TOP_N_AS_HIGH:  3 #from the ranked list of prediction the top N you want to be marked as high likelihood class

BASE_PATH_DATA : "mithun/data/"


LAMBEQ_TRAIN_LAMBEQ_FORMAT_CLAIM: "mc_train_data.txt"
LAMBEQ_TRAIN_LAMBEQ_FORMAT_EVIDENCE: "mc_train_data.txt"
LAMBEQ_TRAIN_LAMBEQ_FORMAT_CLAIM_SMALL: "mc_train_data.txt"
LAMBEQ_TRAIN_LAMBEQ_FORMAT_EVIDENCE_SMALL: "mc_train_data.txt"

LINES_TO_CONVERT : 100 #used to create _small ['all',100]
MNLI_JSON_TRAIN_ORIGINAL: "multinli_1.0_train.jsonl"
MNLI_TRAIN_LAMBEQ_FORMAT_CLAIM: "mnli_train_lambeq_claim.txt"
MNLI_TRAIN_LAMBEQ_FORMAT_EVIDENCE: "mnli_train_lambeq_evidence.txt"
MNLI_TRAIN_LAMBEQ_FORMAT_CLAIM_SMALL: "mnli_train_lambeq_claim_small.txt"
MNLI_TRAIN_LAMBEQ_FORMAT_EVIDENCE_SMALL: "mnli_train_lambeq_evidence_small.txt"

MNLI_JSON_DEV_MISMATCHED_ORIGINAL: "multinli_1.0_dev_mismatched.jsonl"
MNLI_JSON_DEV_MATCHED_ORIGINAL: "multinli_1.0_dev_matched.jsonl"
MNLI_JSON_DEV_MISMATCHED_LAMBEQ_FORMAT_CLAIM: "multinli_1.0_dev_mismatched_lambeq_claim.jsonl"
MNLI_JSON_DEV_MISMATCHED_LAMBEQ_FORMAT_EVIDENCE: "multinli_1.0_dev_mismatched_lambeq_evidence.jsonl"
MNLI_JSON_DEV_MISMATCHED_LAMBEQ_FORMAT_CLAIM_SMALL: "multinli_1.0_dev_mismatched_lambeq_claim_small.jsonl"
MNLI_JSON_DEV_MISMATCHED_LAMBEQ_FORMAT_EVIDENCE_SMALL: "multinli_1.0_dev_mismatched_lambeq_evidence_small.jsonl"

SNLI_JSON_TRAIN_ORIGINAL: "snli_1.0_train.jsonl"
SNLI_TRAIN_LAMBEQ_FORMAT_CLAIM: "snli_train_lambeq_claim.txt"
SNLI_TRAIN_LAMBEQ_FORMAT_EVIDENCE: "snli_train_lambeq_evidence.txt"
SNLI_TRAIN_LAMBEQ_FORMAT_CLAIM_SMALL: "snli_train_lambeq_claim_small.txt"
SNLI_TRAIN_LAMBEQ_FORMAT_EVIDENCE_SMALL: "snli_train_lambeq_evidence_small.txt"
SNLI_DEV_LAMBEQ_FORMAT_CLAIM_SMALL: "snli_dev_lambeq_claim_small.txt"
SNLI_DEV_LAMBEQ_FORMAT_EVIDENCE_SMALL: "snli_dev_lambeq_evidence_small.txt"

LESTAT_TRAIN_LAMBEQ_FORMAT_CLAIM_SMALL: "lestat_train_claim_small.tsv"
LESTAT_TRAIN_LAMBEQ_FORMAT_EVIDENCE_SMALL: "lestat_train_evidence_small.tsv"
LESTAT_DEV_LAMBEQ_FORMAT_CLAIM_SMALL: "lestat_dev_claim_small.tsv"
LESTAT_DEV_LAMBEQ_FORMAT_EVIDENCE_SMALL: "lestat_dev_evidence_small.tsv"

LESTAT_TRAIN_LAMBEQ_FORMAT_CLAIM_MICRO: "lestat_train_claim_micro.tsv"
LESTAT_TRAIN_LAMBEQ_FORMAT_EVIDENCE_MICRO: "lestat_train_evidence_micro.tsv"
LESTAT_DEV_LAMBEQ_FORMAT_CLAIM_MICRO: "lestat_dev_claim_micro.tsv"
LESTAT_DEV_LAMBEQ_FORMAT_EVIDENCE_MICRO: "lestat_dev_evidence_micro.tsv"



LESTAT_DEV_LAMBEQ_FORMAT_CLAIM_GOLD: "lestat_dev_claim_gold.tsv"
LESTAT_DEV_LAMBEQ_FORMAT_EVIDENCE_GOLD: "lestat_dev_evidence_gold.tsv"